/**
 * Pure logic for tools/law-sources.mjs: matches data/hud.json's cites against
 * research/law-sources.json's verified-URL sidecar, and reports the rest.
 *
 * Deliberately does not fetch anything and does not construct a URL from a
 * cite string — research/archive/state-law-matrix-ledger.md's own method log
 * shows a URL pattern that works for most states 404s for two of them, so a
 * guessed URL is not a source, it is a claim that needs the same per-state
 * verification the matrix itself required.
 */

/** Every distinct cite on a HUD line, with the state(s)/line(s) it came from,
 * in a stable order (state, then line id) so output is deterministic. */
export function hudCites(hud) {
  const byCite = new Map()
  for (const code of Object.keys(hud.states).sort()) {
    const st = hud.states[code]
    for (const line of st.lines) {
      if (!line.cite) continue
      const uses = byCite.get(line.cite) ?? []
      uses.push({ state: code, lineId: line.id })
      byCite.set(line.cite, uses)
    }
  }
  return byCite
}

/** New research/law-watch.json source entries for every cite the sidecar has
 * a verified URL for. `existingIds` is the set of ids already in
 * law-watch.json (from either its original 4 or a prior run of this tool) —
 * an id already present is never re-emitted, so a hand-set `hash` baseline
 * is never overwritten by this tool. */
export function matchedSources(hud, sidecar, existingIds) {
  const cites = hudCites(hud)
  const out = []
  const seenThisRun = new Set()
  for (const [cite, uses] of cites) {
    const entry = sidecar[cite]
    if (!entry?.url || !entry?.anchor) continue
    const state = uses[0].state
    const id = idFor(state, cite)
    /* Two different cites can share a truncated slug (real today: 7 of 184
     * cites collide at 40 chars) — checked against BOTH what is already in
     * law-watch.json and what this same run has already emitted, since a
     * silent id collision would make the second real source look
     * "already present" via existingIds.has(id) and get dropped, never
     * watched, with no error. */
    if (existingIds.has(id) || seenThisRun.has(id)) continue
    seenThisRun.add(id)
    out.push({ id, state, cite, url: entry.url, anchor: entry.anchor })
  }
  return out
}

/** State + a hash of the full cite, not a truncated slug of it: two cites
 * that only differ after character 40 of their slugified form (real today,
 * 7 of 184) must not collide. Deterministic, so a re-run always derives the
 * same id for the same cite and existingIds-dedup keeps working. */
function idFor(state, cite) {
  let h = 0
  for (let i = 0; i < cite.length; i++) h = (Math.imul(31, h) + cite.charCodeAt(i)) | 0
  return `hud-${state.toLowerCase()}-${(h >>> 0).toString(36)}`
}

/** Every HUD cite with no sidecar entry, grouped by state, for a human
 * checklist. Each gap lists which line(s) actually show that cite, since
 * that is what a reader needs to go re-derive the citation from. */
export function gaps(hud, sidecar) {
  const cites = hudCites(hud)
  const byState = new Map()
  for (const [cite, uses] of cites) {
    if (sidecar[cite]) continue
    for (const { state, lineId } of uses) {
      const list = byState.get(state) ?? []
      const existing = list.find((g) => g.cite === cite)
      if (existing) existing.lines.push(lineId)
      else list.push({ cite, lines: [lineId] })
      byState.set(state, list)
    }
  }
  return byState
}

export function renderGapsMarkdown(hud, sidecar) {
  const byState = gaps(hud, sidecar)
  const states = [...byState.keys()].sort()
  const total = [...byState.values()].reduce((n, l) => n + l.length, 0)
  const covered = hudCites(hud).size - total
  const lines = [
    '# Law-watch coverage gaps',
    '',
    `Generated by \`node tools/law-sources.mjs --gaps\`. ${covered} of ${covered + total} distinct HUD`,
    'cites have a verified source in research/law-sources.json; the rest are listed below,',
    'grouped by state. Add a URL only after fetching it and confirming the anchor text is',
    'present — see research/law-sources.json\'s own header for the method.',
    '',
  ]
  for (const code of states) {
    lines.push(`## ${code}`, '')
    for (const g of byState.get(code).sort((a, b) => a.cite.localeCompare(b.cite))) {
      lines.push(`- \`${g.cite}\` — ${g.lines.join(', ')}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}
