/* Extends the homepage's existing EN / ES objects; setLang remains the owner. */
window.AmparoCinemaContent = {
  en: {
    eyebrow:'Free practice. Real-world preparedness.',title:'Know what<br>to <em>say.</em>',intro:'Before the moment comes, make the words familiar. Free, bilingual practice for traffic encounters.',small:'About 2 minutes · No account required',scene:'A moment worth preparing for.',scroll:'Discover Amparo',
    proof:['Free to practice','English + Español','Attorney review pending','Your privacy, explained'],
    howLabel:'01 / A little preparation',howHead:'Reading is a start.<br>Practice makes it familiar.',howBody:'Amparo is a practice tool, not a law firm. Rehearse a conversation at your own pace, with room to pause, try again, and learn.',
    steps:[['Choose your moment.','Select your state and a situation. Start with Gentle Mode and a pace that feels comfortable.'],['Find your words.','Read or listen to a prompt, then practice a response. No performance. No audience.'],['Make it familiar.','See the explanation and continue. Repeat a scenario whenever you want.']],
    storyLabel:'02 / Before the knock',storyHead:'Preparation belongs<br>in everyday life.',storyBody:'On the road. At a window. At your door. Some conversations are easier to approach when you have had time to prepare. Start with a moment you can practice today.',storyNote:'Doorstep practice is still under review. Traffic practice is available now.',storyLink:'Start with a traffic stop',
    trustLabel:'03 / Trust, made visible',trustHead:'You should be able<br>to check our work.',trustBody:'Knowing who built the tool is one part. Knowing where the information comes from—and what still needs review—is another.',trustLink:'How we verify',
    trustRows:[['Sources you can follow.','Federal and state information is tied to identified sources. Research, source checks, and attorney review are separate steps.'],['Review status, stated plainly.','Independent attorney review is pending. Amparo provides general information, not legal advice or a guarantee of a safe outcome.'],['Your practice, on your device.','Practice progress and settings stay in this browser. Optional accounts, speech services, and error reporting are explained in our privacy summary.']],
    coverageHead:'Federal foundations.<br>State-specific detail.',coverageBody:'Texas, Georgia, and New York have additional statute citations in the card editions. Other coverage and review status vary. Source-cited does not mean attorney-reviewed.',coverageLink:'Understand the coverage',
    carryLabel:'04 / Keep it within reach',carryHead:'Practice is free.<br>Preparedness can travel.',carryBody:'Learn and rehearse without paying. Optional physical materials are about convenience and distribution—not access to your rights.',
    freeTag:'Available now · Free',freeHead:'Print it. Keep it close.',freeBody:'Build your bilingual cards and print them yourself. Add the details you want to have within reach.',freeLink:'Build free cards',cardsLink:'Explore the six cards',
    kitTag:'Physical product · Prelaunch',kitHead:'A place in your glovebox.',kitBody:'Explore the proposed Amparo Ready Kit. Physical format, contents, and availability still need confirmation. Checkout is not open.',kitLink:'Preview the Ready Kit',
    orgLabel:'05 / Prepared together',orgHead:'Bring the practice<br>to your community.',orgBody:'For the people who help other people prepare. Explore proposed community packages and tell us what your group needs.',orgLink:'For organizations',orgTypes:['Community groups & nonprofits','Schools & driving programs','Libraries & workshop hosts'],
    closeHead:'The moment to practice<br>is <em>before.</em>',closeBody:'A few quiet minutes now. Words that feel more familiar later.',
    footer:['About','How we verify','Privacy','Organizations','Legal aid'],faqTitle:'A few things worth knowing.',
    faq:[['Is practice really free?','Yes. Core practice, English and Spanish, basic printable cards, and legal-aid links are free. Physical products and organization services are optional and currently at prelaunch or inquiry stage.'],['Is this legal advice?','No. Amparo is a practice and information tool, not a law firm. Independent attorney review is pending. Laws and circumstances differ; consult a qualified lawyer for advice about your situation.'],['What happens to my voice?','Amparo does not save a voice recording. If you choose speech recognition, your browser or device provider may process audio. You can use the non-voice practice options.'],['What is stored?','Practice progress and settings are stored in this browser. Optional card accounts store card text you choose to save. Error reports are used for diagnostics. Read the privacy summary for the details.'],['Can my organization use Amparo?','Groups can explore the proposed packages and request information. Pricing, physical materials, facilitation, and availability must be confirmed before any order.'],['Does practice guarantee a safe encounter?','No. Rehearsal can help make words familiar, but cannot control another person’s behavior or guarantee safety or a legal outcome.']],
    disclaimer:'General legal information, not legal advice. Independent attorney review pending. No guarantee of safety or legal outcomes. Amparo is not a law firm.',copyright:'© 2026 Amparo · Preparedness, within reach.'
  },
  es: {
    eyebrow:'Práctica gratuita. Preparación para la vida real.',title:'Sepa qué<br><em>decir.</em>',intro:'Antes de que llegue el momento, familiarícese con las palabras. Práctica gratuita y bilingüe para encuentros de tráfico.',small:'Unos 2 minutos · Sin cuenta obligatoria',scene:'Un momento para el que vale la pena prepararse.',scroll:'Descubra Amparo',
    proof:['Práctica gratuita','English + Español','Revisión jurídica pendiente','Su privacidad, explicada'],
    howLabel:'01 / Un poco de preparación',howHead:'Leer es el principio.<br>Practicar ayuda a recordar.',howBody:'Amparo es una herramienta de práctica, no un bufete. Ensaye una conversación a su ritmo, con espacio para pausar, volver a intentar y aprender.',
    steps:[['Elija su situación.','Seleccione su estado y una situación. Empiece con el Modo Suave y un ritmo que le resulte cómodo.'],['Encuentre sus palabras.','Lea o escuche una indicación y practique una respuesta. Sin actuar para nadie. Sin público.'],['Familiarícese con ellas.','Vea la explicación y continúe. Repita una situación cuando quiera.']],
    storyLabel:'02 / Antes de que toquen',storyHead:'Prepararse es parte<br>de la vida cotidiana.',storyBody:'En la carretera. En una ventanilla. En su puerta. Algunas conversaciones son más fáciles de abordar cuando ha tenido tiempo de prepararse. Empiece con un momento que pueda practicar hoy.',storyNote:'La práctica en la puerta sigue en revisión. La práctica de tráfico ya está disponible.',storyLink:'Empiece con una parada de tráfico',
    trustLabel:'03 / Confianza visible',trustHead:'Debe poder comprobar<br>nuestro trabajo.',trustBody:'Saber quién creó la herramienta es una parte. Saber de dónde viene la información y qué falta por revisar es otra.',trustLink:'Cómo verificamos',
    trustRows:[['Fuentes que puede consultar.','La información federal y estatal se vincula con fuentes identificadas. Investigar, comprobar fuentes y revisar por un abogado son pasos distintos.'],['El estado de revisión, claro.','La revisión independiente por abogados está pendiente. Amparo ofrece información general, no asesoría legal ni una garantía de seguridad.'],['Su práctica, en su dispositivo.','El progreso y los ajustes quedan en este navegador. Las cuentas opcionales, los servicios de voz y los informes de errores se explican en el resumen de privacidad.']],
    coverageHead:'Bases federales.<br>Detalles por estado.',coverageBody:'Texas, Georgia y Nueva York tienen citas legales adicionales en las ediciones de tarjetas. El resto de la cobertura y su revisión varían. Citar fuentes no equivale a una revisión por abogados.',coverageLink:'Conozca la cobertura',
    carryLabel:'04 / Téngalo a mano',carryHead:'Practicar es gratis.<br>La preparación puede viajar.',carryBody:'Aprenda y ensaye sin pagar. Los materiales físicos opcionales ofrecen comodidad y distribución, no acceso a sus derechos.',
    freeTag:'Disponible ahora · Gratis',freeHead:'Imprímalo. Téngalo cerca.',freeBody:'Prepare sus tarjetas bilingües e imprímalas usted mismo. Añada los detalles que desea tener a mano.',freeLink:'Crear tarjetas gratis',cardsLink:'Explorar las seis tarjetas',
    kitTag:'Producto físico · Prelanzamiento',kitHead:'Un lugar en su guantera.',kitBody:'Conozca la propuesta del Amparo Ready Kit. El formato, el contenido y la disponibilidad aún deben confirmarse. Las compras no están abiertas.',kitLink:'Ver la propuesta del Ready Kit',
    orgLabel:'05 / Prepararse juntos',orgHead:'Lleve la práctica<br>a su comunidad.',orgBody:'Para quienes ayudan a otros a prepararse. Explore los paquetes comunitarios propuestos y cuéntenos qué necesita su grupo.',orgLink:'Para organizaciones',orgTypes:['Grupos comunitarios y organizaciones','Escuelas y programas de conducción','Bibliotecas y talleres'],
    closeHead:'El momento de practicar<br>es <em>antes.</em>',closeBody:'Unos minutos tranquilos ahora. Palabras más familiares después.',
    footer:['Acerca de','Cómo verificamos','Privacidad','Organizaciones','Ayuda legal'],faqTitle:'Algunas cosas que conviene saber.',
    faq:[['¿La práctica es realmente gratuita?','Sí. La práctica principal, el inglés y el español, las tarjetas básicas para imprimir y los enlaces de ayuda legal son gratuitos. Los productos físicos y los servicios para organizaciones son opcionales y están en prelanzamiento o consulta.'],['¿Es asesoría legal?','No. Amparo es una herramienta de práctica e información, no un bufete. La revisión independiente por abogados está pendiente. Las leyes y las circunstancias varían; consulte a un abogado para recibir asesoría sobre su situación.'],['¿Qué ocurre con mi voz?','Amparo no guarda una grabación de voz. Si elige reconocimiento de voz, su navegador o proveedor del dispositivo puede procesar el audio. Puede usar las opciones de práctica sin voz.'],['¿Qué se guarda?','El progreso y los ajustes de práctica se guardan en este navegador. Las cuentas opcionales guardan el texto de tarjetas que usted elige guardar. Se utilizan informes de errores para diagnóstico. Consulte el resumen de privacidad.'],['¿Puede usarlo mi organización?','Los grupos pueden explorar los paquetes propuestos y solicitar información. Deben confirmarse precios, materiales físicos, facilitación y disponibilidad antes de cualquier pedido.'],['¿Practicar garantiza un encuentro seguro?','No. Ensayar puede ayudar a familiarizarse con las palabras, pero no controla la conducta de otra persona ni garantiza la seguridad o un resultado legal.']],
    disclaimer:'Información legal general, no asesoría legal. Revisión independiente por abogados pendiente. Sin garantía de seguridad ni de resultados legales. Amparo no es un bufete.',copyright:'© 2026 Amparo · Preparación, a su alcance.'
  }
};
window.amparoCinemaHTML = function(c,L){
  const x=c.cinema, e=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const practice='/rehearse?lang='+L, about=L==='es'?'/acerca/':'/about/', verify=L==='es'?'/como-verificamos/':'/how-we-verify/', privacy=L==='es'?'/privacidad/':'/privacy/';
  const action=(url,label)=>'<a class="cine-action" href="'+url+'">'+e(label)+'</a>';
  const link=(url,label)=>'<a class="cine-link" href="'+url+'">'+e(label)+'</a>';
  const beats=L==='es'?[
    ['Sepa qué','decir.',x.intro,'En la carretera'],
    ['Antes de','que toquen.','Prepararse también es saber qué falta por revisar. La práctica en la puerta aún no está disponible.','En su puerta'],
    ['Llévelo','con usted.','Practique gratis. Imprima sus tarjetas y tenga su plan a mano. Los productos físicos siguen en prelan­zamiento.','Prepárese']
  ]:[['Know what','to say.',x.intro,'On the road'],['Before','the knock.','Preparation also means knowing what still needs review. Doorstep practice is not available yet.','At your door'],['Carry it','with you.','Practice for free. Print your cards and keep your plan close. Physical products remain at prelaunch.','Be prepared']];
  const posters=['/new/assets/cinema-traffic-hero.webp','/new/assets/cinema-doorstep.webp','/new/assets/cinema-three/ready-poster.webp'];
  return '<div class="cinema-page">'+
  '<section class="cine-scroll" id="top" aria-labelledby="cineTitle"><div class="cine-hero"><div class="cine-visual">'+posters.map((src,i)=>'<div class="cine-shot" data-shot="'+i+'"><img src="'+src+'" alt="" '+(i?'loading="lazy"':'fetchpriority="high"')+'><canvas aria-hidden="true" class="cine-canvas"></canvas></div>').join('')+'</div>'+
  '<div class="cine-film-controls"><button class="cine-pause" type="button" hidden></button><a href="#how">'+(L==='es'?'Saltar la película':'Skip the film')+' ↗</a></div>'+
  '<div class="cine-hero-copy"><p class="cine-eyebrow">'+e(x.eyebrow)+'</p><div class="cine-beats">'+beats.map((b,i)=>'<div data-cine-beat="'+i+'"'+(i?' aria-hidden="true"':'')+'><p class="cine-chapter-caption">0'+(i+1)+' / '+e(b[3])+'</p><'+(i?'h2':'h1 id="cineTitle"')+'><span class="cine-line-mask"><span class="cine-line">'+e(b[0])+'</span></span><span class="cine-line-mask cine-emphasis"><span class="cine-line"><span class="cine-outline" aria-hidden="true">'+e(b[1])+'</span><span class="cine-ink">'+e(b[1])+'</span></span></span></'+(i?'h2':'h1')+'><p class="cine-intro">'+e(b[2])+'</p></div>').join('')+'</div><div class="cine-fixed-action">'+action(practice,c.heroCta)+'<p class="cine-small">'+e(x.small)+'</p><p class="cine-small"><a href="'+verify+'">'+e(x.proof[2])+'</a></p></div></div>'+
  '<div class="cine-foot"><div class="cine-progress-meta"><p class="cine-scroll-hint">'+(L==='es'?'Deslice para descubrir':'Scroll to discover')+' ↓</p><span class="cine-frame-label" aria-hidden="true">01 / 03</span></div><div class="cine-timeline" aria-hidden="true"><span class="cine-timeline-fill"></span></div><div class="cine-chapter-nav" role="group" aria-label="'+(L==='es'?'Escenas':'Film chapters')+'">'+beats.map((b,i)=>'<button type="button" data-chapter="'+i+'"><span>0'+(i+1)+'</span> '+e(b[3])+'</button>').join('')+'</div></div></div>'+
  '<div class="cine-static-scenes">'+beats.slice(1).map((b,i)=>'<article><img loading="lazy" src="'+posters[i+1]+'" alt=""><div><p class="cine-chapter-caption">0'+(i+2)+' / '+e(b[3])+'</p><h2>'+e(b[0])+' '+e(b[1])+'</h2><p>'+e(b[2])+'</p></div></article>').join('')+'</div></section>'+
  '<div class="cine-proofbar"><span>'+e(x.proof[0])+'</span><span>'+e(x.proof[1])+'</span><a href="'+verify+'">'+e(x.proof[2])+' ↗</a><a href="'+privacy+'">'+e(x.proof[3])+' ↗</a></div>'+
  '<section class="cine-section" id="how"><p class="cine-eyebrow">'+e(x.howLabel)+'</p><div class="cine-section-head"><h2 class="cine-heading">'+x.howHead+'</h2><p>'+e(x.howBody)+'</p></div><div class="cine-steps">'+x.steps.map((s,i)=>'<article class="cine-step"><span>0'+(i+1)+'</span><h3>'+e(s[0])+'</h3><p>'+e(s[1])+'</p></article>').join('')+'</div></section>'+
  '<section class="cine-story" id="arena"><div class="cine-story-inner"><div class="cine-story-image"><img src="/new/assets/cinema-doorstep.webp" width="1600" height="905" alt="'+(L==='es'?'Escena de arcilla: una puerta cerrada separa al residente dentro y al agente fuera.':'Clay scene: a closed door separates the resident inside from the officer outside.')+'" loading="lazy"><span class="cine-scene-label">02 / 02</span></div><div class="cine-story-copy"><p class="cine-eyebrow">'+e(x.storyLabel)+'</p><h2>'+x.storyHead+'</h2><p>'+e(x.storyBody)+'</p>'+link(practice,x.storyLink)+'<p class="cine-small">'+e(x.storyNote)+'</p></div></div></section>'+
  '<section class="cine-section cine-trust" id="privacy"><div class="cine-trust-intro"><p class="cine-eyebrow">'+e(x.trustLabel)+'</p><h2 class="cine-heading">'+x.trustHead+'</h2><p>'+e(x.trustBody)+'</p>'+link(verify,x.trustLink)+'</div><div class="cine-trust-rows">'+x.trustRows.map((r,i)=>'<article><span>0'+(i+1)+'</span><div><h3>'+e(r[0])+'</h3><p>'+e(r[1])+'</p>'+(i===2?link(privacy,x.proof[3]):'')+'</div></article>').join('')+'</div></section>'+
  '<section class="cine-section cine-edition" id="states"><div><h2>'+x.coverageHead+'</h2><p>'+e(x.coverageBody)+'</p>'+link(verify,x.coverageLink)+'</div><div class="cine-state-tags">'+[['tx','Texas'],['ga','Georgia'],['ny',L==='es'?'Nueva York':'New York']].map(s=>'<a href="/'+(L==='es'?'derechos':'rights')+'/'+s[0]+'/">'+s[1]+' ↗</a>').join('')+'</div></section>'+
  '<section class="cine-carry" id="deal-act" data-manual-deck="true"><div class="cine-section"><p class="cine-eyebrow">'+e(x.carryLabel)+'</p><div class="cine-section-head"><h2 class="cine-heading">'+x.carryHead+'</h2><p>'+e(x.carryBody)+'</p></div><div class="cine-carry-grid"><article class="cine-carry-item"><span class="cine-tag">'+e(x.freeTag)+'</span><h3>'+e(x.freeHead)+'</h3><p>'+e(x.freeBody)+'</p>'+link('/pack?lang='+L,x.freeLink)+'<br><button class="cine-card-open" type="button" onclick="Deal.open()">'+e(x.cardsLink)+'</button></article><article class="cine-carry-item"><span class="cine-tag">'+e(x.kitTag)+'</span><h3>'+e(x.kitHead)+'</h3><p>'+e(x.kitBody)+'</p>'+link('/ready-kit?lang='+L,x.kitLink)+'</article></div></div></section>'+
  '<section class="cine-section cine-community" id="organizations"><div><p class="cine-eyebrow">'+e(x.orgLabel)+'</p><h2>'+x.orgHead+'</h2><p>'+e(x.orgBody)+'</p>'+link('/organizations?lang='+L,x.orgLink)+'</div><ul class="cine-community-types">'+x.orgTypes.map((v,i)=>'<li>'+e(v)+'<span>0'+(i+1)+'</span></li>').join('')+'</ul></section>'+
  '<section class="cine-section cine-faq" id="faq"><h2 class="cine-heading">'+e(x.faqTitle)+'</h2>'+x.faq.map(f=>'<details><summary>'+e(f[0])+'</summary><p>'+e(f[1])+'</p></details>').join('')+'</section>'+
  '<section class="cine-close" id="join"><h2>'+x.closeHead+'</h2><p>'+e(x.closeBody)+'</p>'+action(practice,c.heroCta)+'</section>'+
  '<footer class="cine-footer"><div class="cine-footer-top"><a href="/" class="cine-wordmark">Amparo.</a><div class="cine-footer-links">'+[about,verify,privacy,'/organizations?lang='+L,'/aid?lang='+L].map((url,i)=>'<a href="'+url+'">'+e(x.footer[i])+'</a>').join('')+'</div></div><p>'+e(x.disclaimer)+'</p><p>'+e(x.copyright)+'</p></footer></div>';
};
