/* ============================================================================
   states-data.js — REAL data, extracted verbatim from ../index.html.

   DO NOT HAND-EDIT the rule text, and DO NOT add per-state legal rules here.
   Per the repo's own standard (index.html:2130, research/state-law-matrix.md):
     "NOTHING here is a state statute. Per-state citations arrive only via
      research/state-law-matrix.md, verified and attorney-reviewed."

   TX / GA / NY carry statute-cited rules AND their own curated lifelines.
   Every other jurisdiction gets BASE_RULES (the federal floor) plus pending:true,
   and a lifelines list built from STATE_LEGAL_AID + BASE_LIFELINES — exactly the
   construction at index.html:2227, so both files stay in step.

   ORDER MATTERS: the expansion loop reads STATE_LEGAL_AID and BASE_LIFELINES,
   so those must be declared above it. An earlier build ran the loop first and
   silently produced pending states with no lifelines at all, which made the aid
   page claim it had nothing for Ohio while Ohio Legal Help sat in the data.
   ========================================================================== */

const STATES = {
  TX: { name:"Texas",
    rules_en:["You must show your license when stopped (Transp. Code §521.025). The statute says “display” — some drivers exhibit it through closed glass, but officers and courts often treat that as refusal. Handing it over is the safe way to comply.<br><i class=\"stq\">“…shall…display the license on the demand of a magistrate, court officer, or peace officer.” — Transp. Code §521.025</i>","Get a ticket? Sign it. Signing is only a promise to appear, not an admission of guilt (§543.005) — once you sign, the officer must promptly release you. Refusing to sign is one of the few traffic offenses you can be arrested for.<br><i class=\"stq\">“To secure release, the person arrested must make a written promise to appear in court by signing the written notice.” — Transp. Code §543.005</i>","Digital insurance on your phone is valid proof in Texas.","You are not required to answer questions beyond identifying yourself when lawfully arrested (§38.02); passengers generally do not have to identify themselves unless arrested. But giving a FALSE name, address, or birthdate while lawfully detained is itself a crime (§38.02(b)).<br><i class=\"stq\">“A person commits an offense if he intentionally refuses to give his name, residence address, or date of birth to a peace officer who has lawfully arrested the person.” — Penal Code §38.02(a)</i>","Carrying a handgun? Since Sept. 2021 most adults 21+ may carry without a license (HB 1927). If you DO hold an LTC and an officer asks for ID, the statute says to show the LTC too (Gov't Code §411.205 — the Legislature later repealed the criminal penalty, but showing it is the safe move). Either way: never reach toward the weapon — announce first, move slowly.<br><i class=\"stq\">“…the license holder shall display both the license holder's driver's license…and the license holder's handgun license.” — Gov't Code §411.205</i>","Silence covers questions — not chemical tests. Refusing a breath/blood test after a DWI arrest triggers a license suspension (you have 15 days to request the hearing that contests it) — and police can still get a warrant for your blood. Roadside balance/eye tests before arrest are voluntary in Texas.","Don't drive with this card mounted on the windshield or windows — keep it in the door pocket and present it once stopped."],
    rules_es:["Debe mostrar su licencia cuando lo detienen (Código de Transporte §521.025). La ley dice “exhibir” — algunos la muestran por el vidrio cerrado, pero oficiales y tribunales suelen tratarlo como negativa. Entregarla es la forma segura de cumplir.<br><i class=\"stq\">Texto de la ley (en inglés): “…shall…display the license on the demand of a magistrate, court officer, or peace officer.” — Código de Transporte §521.025</i>","¿Le dan una multa? Fírmela. Firmar es solo una promesa de comparecer, no una admisión de culpa (§543.005) — una vez firmada, el oficial debe dejarlo ir sin demora. Negarse a firmar es una de las pocas infracciones por las que pueden arrestarlo.<br><i class=\"stq\">Texto de la ley (en inglés): “To secure release, the person arrested must make a written promise to appear in court by signing the written notice.” — Código de Transporte §543.005</i>","El seguro digital en su teléfono es prueba válida en Texas.","No está obligado a responder preguntas más allá de identificarse si es arrestado legalmente (§38.02); los pasajeros generalmente no tienen que identificarse a menos que sean arrestados. Pero dar un nombre, dirección o fecha de nacimiento FALSOS estando legalmente detenido es en sí un delito (§38.02(b)).<br><i class=\"stq\">Texto de la ley (en inglés): “A person commits an offense if he intentionally refuses to give his name, residence address, or date of birth to a peace officer who has lawfully arrested the person.” — Código Penal §38.02(a)</i>","¿Porta un arma? Desde sept. de 2021 la mayoría de los adultos de 21+ pueden portar sin licencia (HB 1927). Si SÍ tiene licencia de portación (LTC) y el oficial le pide identificación, la ley dice que muestre también su LTC (Código de Gobierno §411.205 — la Legislatura eliminó después la sanción penal, pero mostrarla es lo más seguro). En todo caso: nunca estire la mano hacia el arma — anuncie primero, muévase despacio.<br><i class=\"stq\">Texto de la ley (en inglés): “…the license holder shall display both the license holder's driver's license…and the license holder's handgun license.” — Código de Gobierno §411.205</i>","El silencio cubre preguntas — no pruebas químicas. Negarse a la prueba de aliento o sangre tras un arresto por DWI suspende su licencia (tiene 15 días para pedir la audiencia que la disputa) — y la policía aún puede obtener una orden judicial para su sangre. Las pruebas de equilibrio/ojos en la calle, antes del arresto, son voluntarias en Texas.","No maneje con esta tarjeta montada en el parabrisas o las ventanas — guárdela en la puerta y preséntela una vez detenido."],
    lifelines:[
      {n:"211 Texas", p:"Dial 211", d_en:"Free public referral line — connects you to local legal aid and services. Anyone can call.", d_es:"Línea pública gratuita de referencias — lo conecta con ayuda legal local. Cualquiera puede llamar.", tags:["free","safe"]},
      {n:"TexasLawHelp.org", p:"texaslawhelp.org/directory", d_en:"Free official directory of legal help across Texas — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Texas — filtrable por condado. Siempre actualizado.", tags:["free","safe"]},
      {n:"State Bar of Texas Referral", n_es:"Colegio de Abogados de Texas — referencias", p:"800-252-9690", d_en:"Matches you to a vetted attorney. $20 for a 30-min consult. Mon–Fri 8:30–4:30 CT.", d_es:"Lo conecta con un abogado verificado. $20 por consulta de 30 min. Lun–Vie 8:30–4:30 CT.", tags:["fee","hrs"]},
      {n:"MigraWatch — United We Dream", p:"1-844-363-1423", d_en:"Free hotline to report ICE activity and get rapid-response, know-your-rights help. Any immigration status.", d_es:"Línea gratuita para reportar actividad de ICE y recibir ayuda de respuesta rápida para conocer sus derechos. Cualquier estatus migratorio.", tags:["free","safe"]},
      {n:"TCOLE — report officer misconduct", n_es:"TCOLE — reportar mala conducta de un oficial", p:"512-936-7700", d_en:"Texas' statewide law-enforcement licensing body. For most complaints, start with the officer's own department — TCOLE handles licensing-level violations and can suspend or revoke an officer's license. Not a lawyer, doesn't award money damages.", d_es:"El organismo estatal que otorga la licencia a los oficiales de Texas. Para la mayoría de las quejas, empiece con el propio departamento del oficial — TCOLE atiende violaciones a nivel de licencia y puede suspender o revocar la licencia de un oficial. No es un abogado, no otorga compensación monetaria.", tags:["free","hrs"]},
      {n:"Direct legal-aid line", n_es:"Línea directa de ayuda legal", p:"Coming soon", d_en:"Partnership pending — added the moment it's confirmed. Scan the QR for the live list.", d_es:"Alianza pendiente — se agrega al confirmarse. Escanea el QR para la lista actualizada.", tags:["soon"]}
    ]},
  GA: { name:"Georgia",
    rules_en:["You must display your license to an officer on request (O.C.G.A. §40-5-29) — handing it over is the safe way to comply.<br><i class=\"stq\">“Every licensee shall have his or her driver's license in his or her immediate possession at all times when operating a motor vehicle” (a); “shall display his or her license upon the demand of a law enforcement officer” (b). — O.C.G.A. §40-5-29(a),(b)</i>","You may remain silent beyond providing your documents — Georgia has no general stop-and-identify law for drivers. But NEVER give a false name (a crime, O.C.G.A. §16-10-25), and in some on-foot situations officers may lawfully demand identification.","Officers may lawfully order you out of the vehicle — comply, keep hands visible, argue later.","Carrying a firearm? Georgia law does not require you to volunteer it — but never reach without announcing; if asked, answer calmly and follow instructions.","Silence covers questions — not chemical tests. Refusing the state test after a DUI arrest suspends your license for a year — you have 30 days to appeal that suspension (O.C.G.A. §40-5-67.1). Under the Georgia Constitution, refusing the breath test cannot be used against you in a criminal trial (Elliott v. State, 2019); refusing a blood test generally still can be. Roadside sobriety tests and the portable roadside breath device are voluntary in Georgia.","Sobriety checkpoints are legal in Georgia. Don't drive with this card mounted — keep it in the door pocket and present it once stopped."],
    rules_es:["Debe mostrar su licencia a un oficial que la pida (O.C.G.A. §40-5-29) — entregarla es la forma segura de cumplir.<br><i class=\"stq\">Texto de la ley (en inglés): “Every licensee shall have his or her driver's license in his or her immediate possession at all times when operating a motor vehicle” (a); “shall display his or her license upon the demand of a law enforcement officer” (b). — O.C.G.A. §40-5-29(a),(b)</i>","Puede guardar silencio más allá de entregar sus documentos — Georgia no tiene una ley general de “identifíquese” para conductores. Pero NUNCA dé un nombre falso (un delito, O.C.G.A. §16-10-25), y en algunas situaciones a pie el oficial sí puede exigir identificación legalmente.","El oficial puede ordenarle legalmente salir del vehículo — cumpla, mantenga las manos visibles, discuta después.","¿Porta un arma? La ley de Georgia no exige que lo informe — pero nunca estire la mano sin anunciarlo; si le preguntan, responda con calma y siga las instrucciones.","El silencio cubre preguntas — no pruebas químicas. Negarse a la prueba estatal tras un arresto por DUI suspende su licencia por un año — tiene 30 días para apelar esa suspensión (O.C.G.A. §40-5-67.1). Bajo la Constitución de Georgia, negarse a la prueba de ALIENTO no puede usarse en su contra en un juicio penal (Elliott v. State, 2019); negarse a una prueba de sangre generalmente sí puede. Las pruebas de sobriedad en la calle y el aparato portátil de aliento son voluntarios en Georgia.","Los retenes de sobriedad son legales en Georgia. No maneje con esta tarjeta montada — guárdela en la puerta y preséntela una vez detenido."],
    lifelines:[
      {n:"211 Georgia", p:"Dial 211", d_en:"Free public referral line — connects you to local legal aid and services. Anyone can call.", d_es:"Línea pública gratuita de referencias — lo conecta con ayuda legal local. Cualquiera puede llamar.", tags:["free","safe"]},
      {n:"GeorgiaLegalAid.org", p:"georgialegalaid.org/find-legal-help", d_en:"Free official directory of legal help across Georgia — routes by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Georgia — dirige según el condado. Siempre actualizado.", tags:["free","safe"]},
      {n:"Georgia NAACP complaints", n_es:"NAACP de Georgia — quejas", p:"404-577-8977", d_en:"Free civil-rights complaint intake (racial profiling). Advocacy, not a law firm. Business hours.", d_es:"Recepción gratuita de quejas de derechos civiles. Apoyo, no es un bufete. Horario de oficina.", tags:["free","hrs"]},
      {n:"MigraWatch — United We Dream", p:"1-844-363-1423", d_en:"Free hotline to report ICE activity and get rapid-response, know-your-rights help. Any immigration status.", d_es:"Línea gratuita para reportar actividad de ICE y recibir ayuda de respuesta rápida para conocer sus derechos. Cualquier estatus migratorio.", tags:["free","safe"]},
      {n:"Direct legal-aid line", n_es:"Línea directa de ayuda legal", p:"Coming soon", d_en:"Partnership pending — added the moment it's confirmed. Scan the QR for the live list.", d_es:"Alianza pendiente — se agrega al confirmarse. Escanea el QR para la lista actualizada.", tags:["soon"]}
    ]},
  NY: { name:"New York",
    rules_en:["You must show your license (VTL §507(2)), registration (§401(4)) and insurance card (§319(3)) when an officer asks — handing them over is the safe way to comply. Failing to show your license is treated as presumptive evidence of driving unlicensed:<br><i class=\"stq\">“Failure by a licensee to exhibit a license valid for operation…to any magistrate…peace officer…or police officer shall be presumptive evidence that he is not duly licensed.” — VTL §507(2)</i>","You may remain silent beyond providing your documents — New York has no stop-and-identify law.","In NYC, the Right to Know Act requires NYPD officers to identify themselves and explain the stop; in many stops they must offer a business card (summons or arrest paperwork can substitute). Before a consent search they must tell you that you can refuse, and document your consent.","If ordered out of the vehicle — or told to lower the window fully — comply. Hands visible, move slowly, argue later.","Silence covers questions — not chemical tests. Refusing the official breath/blood test after a DWI arrest costs your license for at least a year plus a civil penalty (VTL §1194), even if you're never convicted. The ROADSIDE is different in NY: refusing the roadside breath screening is itself a traffic infraction (VTL §1194(1)(b)), and refusing balance/eye tests can be brought up in court. Sobriety checkpoints are legal in NY.<br><i class=\"stq\">“…a revoked license…shall not be restored for at least one year after such revocation.” — VTL §1194(2)(d)(1)(a)</i>","Carrying a licensed firearm? NY does not require you to volunteer it — never reach toward it; if asked, answer that one question and follow instructions.","Never drive with this card mounted on the windshield or front side windows (VTL §375(12-a)) — keep it in the door pocket and hold it up only after you've stopped.<br><i class=\"stq\">“No person shall drive any motor vehicle with any sign or other nontransparent material…upon the front windshield or the sidewings or side windows…forward of or adjacent to the operator's seat.” — VTL §375(12-a)</i>"],
    rules_es:["Debe mostrar su licencia (VTL §507(2)), registro (§401(4)) y tarjeta de seguro (§319(3)) cuando el oficial se los pida — entregarlos es la forma segura de cumplir. No mostrar la licencia se trata como evidencia presuntiva de manejar sin licencia:<br><i class=\"stq\">Texto de la ley (en inglés): “Failure by a licensee to exhibit a license valid for operation…to any magistrate…peace officer…or police officer shall be presumptive evidence that he is not duly licensed.” — VTL §507(2)</i>","Puede guardar silencio más allá de entregar sus documentos — Nueva York no tiene ley de “identifíquese”.","En NYC, la ley Right to Know exige que los oficiales de NYPD se identifiquen y expliquen la parada; en muchas paradas deben ofrecer una tarjeta (la multa o el acta de arresto puede sustituirla). Antes de un registro por consentimiento deben decirle que puede negarse, y documentar su consentimiento.","Si le ordenan salir del vehículo — o bajar la ventana por completo — cumpla. Manos visibles, movimientos lentos, discuta después.","El silencio cubre preguntas — no pruebas químicas. Negarse a la prueba OFICIAL de aliento o sangre tras un arresto por DWI le cuesta la licencia al menos un año más una multa civil (VTL §1194), aunque nunca lo condenen. En la CALLE es distinto en NY: negarse a la prueba preliminar de aliento es en sí una infracción de tránsito (VTL §1194(1)(b)), y negarse a las pruebas de equilibrio/ojos puede mencionarse en la corte. Los retenes de sobriedad son legales en NY.<br><i class=\"stq\">Texto de la ley (en inglés): “…a revoked license…shall not be restored for at least one year after such revocation.” — VTL §1194(2)(d)(1)(a)</i>","¿Porta un arma con licencia? NY no exige que lo informe — nunca estire la mano hacia ella; si le preguntan, responda solo eso y siga instrucciones.","Nunca maneje con esta tarjeta montada en el parabrisas o ventanas delanteras (VTL §375(12-a)) — guárdela en la puerta y muéstrela solo después de detenerse.<br><i class=\"stq\">Texto de la ley (en inglés): “No person shall drive any motor vehicle with any sign or other nontransparent material…upon the front windshield or the sidewings or side windows…forward of or adjacent to the operator's seat.” — VTL §375(12-a)</i>"],
    lifelines:[
      {n:"211 New York", p:"Dial 211", d_en:"Free public referral line — connects you to local legal aid and services. Anyone can call.", d_es:"Línea pública gratuita de referencias — lo conecta con ayuda legal local. Cualquiera puede llamar.", tags:["free","safe"]},
      {n:"LawHelpNY.org", p:"lawhelpny.org/find-legal-help", zipParam:"coverage_area", d_en:"Free official directory of legal help across New York — search by county or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Nueva York — busca por condado o código postal. Siempre actualizado.", tags:["free","safe"]},
      {n:"CCRB — police complaints (NYC only)", n_es:"CCRB — quejas contra la policía (solo NYC)", p:"1-800-341-2272", d_en:"Free complaint agency for NYPD officers only (stops, searches, force). Outside NYC, complain to the local department or NY State Police. Not a lawyer — it investigates. CCRB does not ask about immigration status.", d_es:"Agencia gratuita de quejas solo para oficiales de NYPD. Fuera de NYC, presente su queja al departamento local o a la Policía Estatal. No es un abogado — investiga. La CCRB no pregunta sobre estatus migratorio.", tags:["free","safe","hrs"]},
      {n:"NYS New Americans Hotline", n_es:"NYS — Línea para Nuevos Estadounidenses", p:"1-800-566-7636", d_en:"Free, confidential immigration help and referrals statewide (Mon–Fri). Any immigration status — interpreters available.", d_es:"Ayuda migratoria gratuita y confidencial en todo el estado (lun–vie). Cualquier estatus — hay intérpretes.", tags:["free","safe","hrs"]},
      {n:"Direct legal-aid line", n_es:"Línea directa de ayuda legal", p:"Coming soon", d_en:"Partnership pending — added the moment it's confirmed. Scan the QR for the live list.", d_es:"Alianza pendiente — se agrega al confirmarse. Escanea el QR para la lista actualizada.", tags:["soon"]}
    ]}
};

const US_STATE_NAMES = {
  AL:"Alabama", AK:"Alaska", AZ:"Arizona", AR:"Arkansas", CA:"California",
  CO:"Colorado", CT:"Connecticut", DE:"Delaware", DC:"District of Columbia",
  FL:"Florida", GA:"Georgia", HI:"Hawaii", ID:"Idaho", IL:"Illinois",
  IN:"Indiana", IA:"Iowa", KS:"Kansas", KY:"Kentucky", LA:"Louisiana",
  ME:"Maine", MD:"Maryland", MA:"Massachusetts", MI:"Michigan", MN:"Minnesota",
  MS:"Mississippi", MO:"Missouri", MT:"Montana", NE:"Nebraska", NV:"Nevada",
  NH:"New Hampshire", NJ:"New Jersey", NM:"New Mexico", NY:"New York",
  NC:"North Carolina", ND:"North Dakota", OH:"Ohio", OK:"Oklahoma",
  OR:"Oregon", PA:"Pennsylvania", RI:"Rhode Island", SC:"South Carolina",
  SD:"South Dakota", TN:"Tennessee", TX:"Texas", UT:"Utah", VT:"Vermont",
  VA:"Virginia", WA:"Washington", WV:"West Virginia", WI:"Wisconsin", WY:"Wyoming"
};

const BASE_RULES_EN = [
  "Show your licence, registration and proof of insurance when the officer asks. Every state requires this while you're driving — the part you control is HOW: announce the reach before you make it, move slowly, keep your hands visible.",
  "The officer can order you — and your passengers — out of the car, even with no suspicion that anyone did anything wrong.<br><i class=\"stq\">Pennsylvania v. Mimms, 434 U.S. 106 (1977); Maryland v. Wilson, 519 U.S. 408 (1997)</i>",
  "Silence is your right, but you have to claim it out loud. Just going quiet is not enough — say it: “I'm using my right to remain silent.”<br><i class=\"stq\">Berghuis v. Thompkins, 560 U.S. 370 (2010); Salinas v. Texas, 570 U.S. 178 (2013)</i>",
  "You can refuse a search — “I don't consent to any searches, officer.” Refusing is not evidence against you, and by itself it does not give an officer a reason to search.",
  "A stop cannot be stretched out to wait for a drug dog unless there's separate reasonable suspicion. Once the reason for the stop is finished, holding you longer needs its own justification.<br><i class=\"stq\">Rodriguez v. United States, 575 U.S. 348 (2015)</i>",
  "Never physically resist — not even an order you're sure is unlawful. You win later, on paper, with a lawyer. Nobody wins on the roadside.",
  "⚠️ <b>Your state's own rules aren't verified in Amparo yet.</b> Everything above is federal law and applies everywhere. What varies by state — whether you must give your name, whether refusing to sign a ticket can get you arrested, and whether you may record audio without telling the officer — is NOT shown for your state, because we won't print a rule we haven't checked against the statute."
];

const BASE_RULES_ES = [
  "Muestre su licencia, registro y prueba de seguro cuando el oficial se los pida. Todos los estados lo exigen mientras maneja — lo que usted controla es CÓMO: anuncie el movimiento antes de hacerlo, muévase despacio, mantenga las manos a la vista.",
  "El oficial puede ordenarle a usted — y a sus pasajeros — bajar del auto, aunque no sospeche que alguien hizo algo malo.<br><i class=\"stq\">Pennsylvania v. Mimms, 434 U.S. 106 (1977); Maryland v. Wilson, 519 U.S. 408 (1997)</i>",
  "El silencio es su derecho, pero tiene que invocarlo en voz alta. Quedarse callado no basta — dígalo: «Estoy usando mi derecho a guardar silencio.»<br><i class=\"stq\">Berghuis v. Thompkins, 560 U.S. 370 (2010); Salinas v. Texas, 570 U.S. 178 (2013)</i>",
  "Puede negarse a un registro — «No doy consentimiento para ningún registro, oficial.» Negarse no es prueba en su contra, y por sí solo no le da al oficial una razón para registrar.",
  "No pueden alargar la parada para esperar a un perro antidrogas sin una sospecha razonable aparte. Una vez terminado el motivo de la parada, retenerlo más tiempo necesita su propia justificación.<br><i class=\"stq\">Rodriguez v. United States, 575 U.S. 348 (2015)</i>",
  "Nunca se resista físicamente — ni siquiera a una orden que usted sabe que es ilegal. Se gana después, en papel, con un abogado. Nadie gana en la carretera.",
  "⚠️ <b>Las reglas propias de su estado aún no están verificadas en Amparo.</b> Todo lo anterior es ley federal y aplica en todas partes. Lo que cambia según el estado — si debe dar su nombre, si negarse a firmar una multa puede llevar a un arresto, y si puede grabar audio sin avisarle al oficial — NO se muestra para su estado, porque no imprimimos una regla que no hemos verificado contra la ley."
];

const STATE_LEGAL_AID = {
  AL:{n:"AlabamaLegalHelp.org", p:"www.alabamalegalhelp.org/find-legal-help/directory", d_en:"Free official directory of legal help across Alabama — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Alabama — busca por ciudad, condado o código postal. Siempre actualizado."},
  AZ:{n:"AZLawHelp.org", p:"azlawhelp.org/directory", d_en:"Free official directory of legal help across Arizona — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Arizona — filtrable por condado. Siempre actualizado."},
  CA:{n:"LawHelpCA.org", p:"www.lawhelpca.org/find-legal-help", d_en:"Free official directory of legal help across California — filterable by county or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en California — filtrable por condado o código postal. Siempre actualizado."},
  DC:{n:"LawHelp.org — DC", p:"lawhelp.org/dc/find-legal-help", zipParam:"location", d_en:"Free official directory of legal help across Washington, DC — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Washington, DC — busca por ciudad, condado o código postal. Siempre actualizado."},
  FL:{n:"FloridaLawHelp.org", p:"floridalawhelp.org/find-provider", d_en:"Free official directory of legal help across Florida — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Florida — filtrable por condado. Siempre actualizado."},
  IL:{n:"IllinoisLegalAid.org", p:"illinoislegalaid.org/get-legal-help", d_en:"Free official directory of legal help across Illinois — search by ZIP, filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Illinois — busca por código postal, filtrable por condado. Siempre actualizado."},
  IN:{n:"Indiana Legal Help", p:"indianalegalhelp.org/get-help/", d_en:"Free official directory of legal help across Indiana — search by ZIP or county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Indiana — busca por código postal o condado. Siempre actualizado."},
  KY:{n:"Kentucky Justice Online", p:"kyjustice.org/help-near-you", d_en:"Free official directory of legal help across Kentucky — browse by county map or search. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Kentucky — explora por mapa de condado o busca. Siempre actualizado."},
  LA:{n:"LouisianaLawHelp.org", p:"louisianalawhelp.org/find-legal-help/directory/", d_en:"Free official directory of legal help across Louisiana — location-aware map and search. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Luisiana — mapa y búsqueda según tu ubicación. Siempre actualizado."},
  MD:{n:"Maryland Legal Aid", p:"mdlab.org/contact-us/", d_en:"Free official directory of legal help across Maryland — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Maryland — busca por ciudad, condado o código postal. Siempre actualizado."},
  MA:{n:"Massachusetts Legal Resource Finder", p:"masslrf.org", d_en:"Free official directory of legal help across Massachusetts — answer a few questions to get matched to help near you. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Massachusetts — responde unas preguntas para encontrar ayuda cerca de ti. Siempre actualizado."},
  MI:{n:"Michigan Legal Help", p:"michiganlegalhelp.org/organizations-and-courts/self-help-centers", d_en:"Free official directory of legal help across Michigan — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Míchigan — filtrable por condado. Siempre actualizado."},
  MN:{n:"LawHelp Minnesota", p:"lawhelpmn.org/providers-and-clinics", d_en:"Free official directory of legal help across Minnesota — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Minnesota — filtrable por condado. Siempre actualizado."},
  MS:{n:"MSLegalServices.org", p:"www.mslegalservices.org/find-legal-help/directory", d_en:"Free official directory of legal help across Mississippi — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Misisipi — busca por ciudad, condado o código postal. Siempre actualizado."},
  MT:{n:"Montana LawHelp", p:"montanalawhelp.org/find-legal-providers", d_en:"Free official directory of legal help across Montana — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Montana — filtrable por condado. Siempre actualizado."},
  NC:{n:"LawHelpNC.org", p:"www.lawhelpnc.org/get-help-from-a-lawyer", d_en:"Free official directory of legal help across North Carolina — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Carolina del Norte — busca por ciudad, condado o código postal. Siempre actualizado."},
  OH:{n:"Ohio Legal Help", p:"ohiolegalhelp.org/find-your-legal-aid", d_en:"Free official directory of legal help across Ohio — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Ohio — filtrable por condado. Siempre actualizado."},
  OR:{n:"Oregon Law Help", p:"oregonlawhelp.org/Search-for-lawyers-legal-help", d_en:"Free official directory of legal help across Oregon — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Oregón — filtrable por condado. Siempre actualizado."},
  PA:{n:"PALawHELP.org", p:"www.palawhelp.org/find-legal-help/directory", d_en:"Free official directory of legal help across Pennsylvania — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Pensilvania — busca por ciudad, condado o código postal. Siempre actualizado."},
  SC:{n:"LawHelp.org — SC", p:"lawhelp.org/sc/find-legal-help", zipParam:"location", d_en:"Free official directory of legal help across South Carolina — search by city, county, or ZIP. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Carolina del Sur — busca por ciudad, condado o código postal. Siempre actualizado."},
  TN:{n:"Justice For All TN", p:"justiceforalltn.org/resources/", d_en:"Free official directory of legal help across Tennessee — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Tennessee — filtrable por condado. Siempre actualizado."},
  VA:{n:"Virginia Law Help", p:"virginialawhelp.org/en/get-legal-help", d_en:"Free official directory of legal help across Virginia — filterable by city or county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Virginia — filtrable por ciudad o condado. Siempre actualizado."},
  WA:{n:"Washington Law Help", p:"washingtonlawhelp.org/en/get-legal-help", d_en:"Free official directory of legal help across Washington — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Washington — filtrable por condado. Siempre actualizado."},
  WI:{n:"Wisconsin Law Help", p:"wislawhelp.org/legal-resource-directory", d_en:"Free official directory of legal help across Wisconsin — filterable by county. Always current.", d_es:"Directorio oficial gratuito de ayuda legal en Wisconsin — filtrable por condado. Siempre actualizado."}
};

const BASE_LIFELINES = [
  /* Added 2026-08-16, real user driven: a stranger messaged the operator on
     Facebook asking to find a pro bono lawyer near them, in a state without
     researched lifelines. Verified live (WebFetch/WebSearch) before adding:
     lawhelp.org/find-help is a real, maintained state-by-state directory
     finder run by Pro Bono Net, the same nonprofit consortium behind
     TexasLawHelp/GeorgiaLegalAid/LawHelpNY below. Deliberately a link to
     THEIR infrastructure, not a scraped/mirrored lawyer list Amparo would
     have to keep current and be liable for — see
     notebook/amparo-directory-feasibility-2026-08-16.md for why. */
  {n:"LawHelp.org — find help in your state", n_es:"LawHelp.org — encuentra ayuda en tu estado", p:"lawhelp.org/find-help", d_en:"Free national directory. Pick your state to find legal aid organizations near you, often filterable by county.", d_es:"Directorio nacional gratuito. Elige tu estado para encontrar organizaciones de ayuda legal cerca de ti, a menudo filtrable por condado.", tags:["free","safe"]},
  {n:"Find your state's ACLU affiliate", n_es:"Encuentra la filial de ACLU de tu estado", p:"aclu.org/affiliates", d_en:"Every state has one. They publish state-specific know-your-rights guidance and take reports of rights violations. Not your lawyer, but the right first call.", d_es:"Cada estado tiene una. Publican guías de derechos específicas del estado y reciben reportes de violaciones. No es su abogado, pero es la primera llamada correcta.", tags:["free","safe"]},
  {n:"Legal aid + social services referral", n_es:"Ayuda legal + referencia a servicios sociales", p:"Dial 211", d_en:"Free nationwide referral line. Ask for legal aid in your county — they route you to the office that covers your area.", d_es:"Línea gratuita nacional de referencias. Pida ayuda legal en su condado — lo dirigen a la oficina de su área.", tags:["free","hrs"]},
  {n:"MigraWatch — United We Dream", p:"1-844-363-1423", d_en:"Free hotline to report ICE activity and get rapid-response, know-your-rights help. Any immigration status.", d_es:"Línea gratuita para reportar actividad de ICE y recibir ayuda de respuesta rápida. Cualquier estatus migratorio.", tags:["free","safe"]},
  {n:"988 Suicide & Crisis Lifeline", n_es:"988 Línea de Suicidio y Crisis", p:"988", d_en:"If a stop leaves you shaken. Free, 24/7, confidential — call or text.", d_es:"Si una parada lo deja alterado. Gratis, 24/7, confidencial — llame o envíe mensaje.", tags:["free","safe"]}
];

/* index.html:lnName — lifeline NAMES carry n_es only where a translation
   exists; proper nouns (211 X, MigraWatch, *.org) deliberately do not. */
function lnName(L, lang){ return (lang === 'es' && L.n_es) ? L.n_es : L.n; }

/* Every jurisdiction selectable, no dead ends, no undefined. */
Object.keys(US_STATE_NAMES).forEach(function(k){
  if (STATES[k]) return;
  var extra = STATE_LEGAL_AID[k];
  STATES[k] = {
    name: US_STATE_NAMES[k], pending: true,
    rules_en: BASE_RULES_EN, rules_es: BASE_RULES_ES,
    lifelines: extra ? [Object.assign({}, extra, { tags: ['free','safe'] })].concat(BASE_LIFELINES)
                     : BASE_LIFELINES
  };
});

/* The three lines Stress Mode shows. Verbatim from the Arena script
   (arena/index.html:725-744) — already in attorney review. They are FEDERAL and
   identical in every state, which is exactly why they are safe for all 50.
   Nothing here varies by state. */
var STRESS_PHRASES = {
  en: ["I choose to remain silent.", "I do not consent to a search.", "Am I free to go?"],
  es: ["Elijo guardar silencio.", "No doy consentimiento a un registro.", "¿Soy libre de irme?"]
};

window.AmparoData = { STATES: STATES, US_STATE_NAMES: US_STATE_NAMES, STRESS_PHRASES: STRESS_PHRASES,
                      STATE_LEGAL_AID: STATE_LEGAL_AID, BASE_LIFELINES: BASE_LIFELINES, lnName: lnName };
