/* The Panic HUD's view model. Pure: takes the hud bank as an argument so it is
 * testable with node --test and the React view stays a thin renderer.
 *
 * Every word here comes from content/hud.json (generated by
 * tools/build-jurisdictions.mjs); nothing user-facing is authored in /app. */

export type HudLine = { id: string; posture: string; cite: string | null; verdict: string; en: string; es: string }
export type HudState = {
  code: string
  name: string
  nameEs?: string
  review: { primaryText: boolean; attorney: boolean; attorneyReviewedBy: unknown }
  notice: { en: string; es: string }
  remedyTier: number | null
  lines: HudLine[]
}
export type HudUi = Record<string, { en: string; es: string }>
export type HudBank = { version: number; sourceHash: string; ui: HudUi; federal: HudLine[]; states: Record<string, HudState> }
export type Lang = 'en' | 'es'

export type HudViewLine = { id: string; text: string; cite: string | null; flag: 'likely' | null; emphasis: boolean }
export type HudView = {
  stateCode: string | null
  stateName: string | null
  provisional: boolean
  reviewed: boolean
  notice: string
  lines: HudViewLine[]
}

/** Panic order: what to say first, then what changes by state. */
const ORDER = ['safety', 'silence', 'documents', 'search', 'sign', 'passenger', 'firearm', 'recording', 'unmarked', 'reason', 'footage']

/** Postures where the state differs from the national default in a way that
 * changes what you do on the shoulder. Rendered with the gold rule. */
const EMPHASIS = new Set([
  'crime', 'arrest_trigger', 'firearm_any_occupant', 'proactive', 'refusal_offense_limited',
  'cannabis_caselaw', 'cannabis_statute', 'cannabis_both', 'flat_bar', 'lying_is_crime',
])

const STATE_CODE = /^[A-Z]{2}$/

export function isKnownState(code: unknown, bank: HudBank): code is string {
  return typeof code === 'string' && STATE_CODE.test(code) && code in bank.states
}

/** The compiled sentence carries its cite inline, "(§...)", so it stands alone
 * in plain text. The HUD renders the cite as its own gold line, so it is
 * lifted out of the sentence here rather than read twice. */
export function withoutInlineCite(text: string, cite: string | null): string {
  return cite ? text.split(` (${cite})`).join('') : text
}

function toView(l: HudLine, lang: Lang): HudViewLine {
  return { id: l.id, text: withoutInlineCite(l[lang], l.cite), cite: l.cite, flag: l.verdict === 'LIKELY' ? 'likely' : null, emphasis: EMPHASIS.has(l.posture) }
}

export function hudFor(code: string | null | undefined, lang: Lang, bank: HudBank): HudView {
  if (!isKnownState(code, bank)) {
    return {
      stateCode: null,
      stateName: null,
      provisional: true,
      reviewed: false,
      notice: bank.ui.federalNotice[lang],
      lines: bank.federal.map((l) => toView(l, lang)),
    }
  }
  const st = bank.states[code]
  const byId = new Map(st.lines.map((l) => [l.id, l]))
  const lines = ORDER.map((id) => byId.get(id)).filter((l): l is HudLine => !!l).map((l) => toView(l, lang))
  return {
    stateCode: st.code,
    stateName: lang === 'es' ? (st.nameEs ?? st.name) : st.name,
    provisional: !st.review.attorney,
    reviewed: st.review.attorney,
    notice: st.notice[lang],
    lines,
  }
}

/** `?state=XX` on the URL wins over the saved pack, so a printed card or a
 * link can open the HUD on the right state without a tap. */
export function stateFromSearch(search: string, bank: HudBank): string | null {
  const v = new URLSearchParams(search).get('state')
  const code = v ? v.toUpperCase() : ''
  return isKnownState(code, bank) ? code : null
}
